steps:
  - name: gcr.io/cloud-builders/docker
    id: backend
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:latest
      - backend

  - name: gcr.io/cloud-builders/docker
    id: frontend
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - frontend

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:latest
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest

substitutions:
  _REGION: us-central1
  _REPOSITORY: cinemaclub
  _VITE_API_BASE_URL: http://backend:4000/api
  _TAG: dev

options:
  logging: CLOUD_LOGGING_ONLY
